mi_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('create_player/',views.crear_jugador, name='crear_jugador'),
    path('create_director/',views.crear_director, name='crear_director'),
    path('create_equipo/',views.crear_equipo, name='crear_equipo'),
    path('create_liga/',views.crear_liga, name='crear_liga'),
    path('create_estadio/',views.crear_estadio, name='crear_estadio'),
    path('create_arbitro/',views.crear_arbitro, name='crear_arbitro'),
    path('create_juego/',views.crear_juego, name='crear_juego'),
    path('jugadores/', views.lista_jugadores, name='lista_jugadores'),
    path('directores/', views.lista_directores, name='lista_directores'),
    path('equipos/', views.lista_equipos, name='lista_equipos'),
    path('ligas/', views.lista_liga, name='lista_liga'),
    path('estadios/', views.lista_estadios, name='lista_estadios'),
    path('arbitros/', views.lista_arbitros, name='lista_arbitros'),
    path('juegos/', views.lista_juegos, name='lista_juegos'),
    path('equipos/<int:id>', views.equipo_detail, name='equipo_detail'),
    path('ligas/<int:id>', views.liga_detail, name='liga_detail'),
    
]

mi_projecto/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mi_app.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mi_proyecto/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mi_app.urls'))
]

mi_app/models.py
from django.db import models


class Directores(models.Model):
    name = models.CharField(max_length=200)
    foto = models.ImageField(upload_to='directores/')

    def __str__(self):
        return self.name

class Ligas(models.Model):
    name = models.CharField(max_length=200)
    foto = models.ImageField(upload_to='ligas/')
    
    def __str__(self):
        return self.name

class Equipos(models.Model):
    name = models.CharField(max_length=200)
    foto = models.ImageField(upload_to='equipos/')
    directores = models.ForeignKey(Directores, on_delete=models.SET_NULL,null=True,related_name='equipos_directores')
    ligas = models.ForeignKey(Ligas, on_delete=models.SET_NULL,null=True,related_name='equipos_ligas')
    
    def __str__(self):
        return self.name

class Jugadores(models.Model):
    STATE_CHOICES = [
        ('del', 'Delantero'),
        ('def', 'Defensa'),
        ('med', 'Medio Campista'),
        ('ban_der', 'Banda Derecha'),
        ('ban_izq', 'Banda Izquierda'),
        ('por', 'Portero'),
        
    ]

    name = models.CharField(max_length=200)
    posicion = models.CharField(max_length=200,choices=STATE_CHOICES)
    num_player = models.CharField(max_length=200)
    foto = models.ImageField(upload_to='jugadores/')
    equipo_id = models.ForeignKey(Equipos, on_delete=models.SET_NULL,null=True,related_name='jugadores_equipos')

    def __str__(self):
        return self.name
    


class Arbitros(models.Model):
    name = models.CharField(max_length=200)
    liga_id = models.ForeignKey(Ligas,on_delete=models.SET_NULL,null=True,related_name='arbitro_liga')
    foto = models.ImageField(upload_to='arbitros/')

    def __str__(self):
        return self.name


class Estadios(models.Model):
    name = models.CharField(max_length=200)
    liga_id = models.ForeignKey(Ligas, on_delete=models.SET_NULL,null=True,related_name='liga_estadio')
    foto = models.ImageField(upload_to='estadios/')

    def __str__(self):
        return self.name


class Eventos(models.Model):
    player_id = models.ForeignKey(Jugadores, on_delete=models.SET_NULL,null=True)
    tipo = models.CharField(max_length=200)
    minuto = models.CharField(max_length=200)
    tarjeta = models.CharField(max_length=200)


class Juegos(models.Model):
    STATE_CHOICES = [
        ('programado', 'Programado'),
        ('terminado', 'Terminado'),
    ]

    folio = models.CharField(max_length=200)
    fecha = models.DateField()
    liga_id = models.ForeignKey(Ligas, on_delete=models.SET_NULL,null=True)
    equipo1 = models.ForeignKey(Equipos, on_delete=models.SET_NULL,null=True,related_name='juegos_equipo1')
    equipo2 = models.ForeignKey(Equipos, on_delete=models.SET_NULL,null=True,related_name='juegos_equipo2')
    estadio = models.ForeignKey(Estadios, on_delete=models.SET_NULL,null=True)
    arbitro = models.ForeignKey(Arbitros,on_delete=models.SET_NULL,null=True)
    state = models.CharField(max_length=20, choices=STATE_CHOICES, default='programado')

mi_app/forms.py
from django import forms
from .models import Jugadores, Directores, Equipos, Ligas, Estadios, Arbitros, Juegos

class JugadorForm(forms.ModelForm):
    class Meta:
        model = Jugadores
        fields = ('name', 'posicion', 'num_player','equipo_id' ,'foto')

class DirectorForm(forms.ModelForm):
    class Meta:
        model = Directores
        fields = ('name', 'foto')

class EquiposForm(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = ('name', 'foto', 'directores','ligas')


class LigasForm(forms.ModelForm):
    class Meta:
        model = Ligas
        fields = ('name', 'foto')

class EstadiosForm(forms.ModelForm):
    class Meta:
        model = Estadios
        fields = ('name','liga_id' ,'foto')

        

class ArbitrosForm(forms.ModelForm):
    class Meta:
        model = Arbitros
        fields = ('name' ,'foto','liga_id')

        

class JuegosForm(forms.ModelForm):

    fecha = forms.DateField(
        label='Fecha',
        widget=forms.DateInput(attrs={'class': 'datepicker', 'type': 'date'}),
    )

    class Meta:
        model = Juegos
        fields = ('folio' ,'fecha','liga_id', 'equipo1', 'equipo2', 'estadio', 'arbitro', 'state')

mi_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from .forms import JugadorForm, DirectorForm, EquiposForm, LigasForm, EstadiosForm, ArbitrosForm, JuegosForm
from .models import Jugadores, Directores, Equipos, Ligas, Estadios, Arbitros, Juegos

def index(request):
    title = "Manager Teams"
    return render(request,'index.html')

from .forms import JugadorForm

def crear_jugador(request):
    if request.method == 'POST':
        form = JugadorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Redirigir o realizar alguna acción adicional
    else:
        form = JugadorForm()
    return render(request, 'crear_jugador.html', {'form': form})

def crear_director(request):
    if request.method == 'POST':
        form = DirectorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Redirigir o realizar alguna acción adicional
    else:
        form = DirectorForm()
    return render(request, 'crear_director.html', {'form': form})


def crear_equipo(request):
    if request.method == 'POST':
        form = EquiposForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            # Redirigir o realizar alguna acción adicional
    else:
        form = EquiposForm()
    return render(request, 'crear_equipo.html', {'form': form})


def crear_liga(request):
    if request.method == 'POST':
        form = LigasForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            # Redirigir o realizar alguna acción adicional
    else:
        form = LigasForm()
    return render(request, 'crear_liga.html', {'form': form})


def crear_estadio(request):
    if request.method == 'POST':
        form = EstadiosForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Redirigir o realizar alguna acción adicional
    else:
        form = EstadiosForm()
    return render(request, 'crear_estadio.html', {'form': form})


def crear_arbitro(request):
    if request.method == 'POST':
        form = ArbitrosForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Redirigir o realizar alguna acción adicional
    else:
        form = ArbitrosForm()
    return render(request, 'crear_arbitro.html', {'form': form})


def crear_juego(request):
    if request.method == 'POST':
        form = JuegosForm(request.POST, request.FILES)
        if form.is_valid():
            juego = form.save(commit=False)  # Obtener instancia del juego sin guardar en la base de datos
            equipo1 = juego.equipo1
            equipo2 = juego.equipo2

            if equipo1.ligas.id != equipo2.ligas.id:
                form.add_error(None, "Los equipos no pertenecen a la misma liga.")
            else:
                juego.save()  # Guardar el juego en la base de datos si pasa la validación

    else:
        form = JuegosForm()
    return render(request, 'crear_juego.html', {'form': form})


def equipo_detail(request,id):
    equipo = get_object_or_404(Equipos, id=id)
    jugadores = Jugadores.objects.filter(equipo_id=id)
    return render(request, 'equipo_detail.html', {
        'equipo': equipo,
        'jugadores':jugadores
    })

def liga_detail(request,id):
    liga = get_object_or_404(Ligas, id=id)
    equipos = Equipos.objects.filter(ligas_id=id)
    return render(request, 'liga_detail.html', {
        'liga': liga,
        'equipos': equipos
    })


def lista_equipos(request):
    equipos = Equipos.objects.all()
    return render(request, 'equipos_list.html', {'equipos': equipos})

def lista_liga(request):
    ligas = Ligas.objects.all()
    return render(request, 'liga_list.html', {'ligas': ligas})


def lista_estadios(request):
    estadios = Estadios.objects.all()
    return render(request, 'estadios_list.html', {'estadios': estadios})


def lista_arbitros(request):
    arbitros = Arbitros.objects.all()
    return render(request, 'arbitros_list.html', {'arbitros': arbitros})

def lista_jugadores(request):
    jugadores = Jugadores.objects.all()
    return render(request, 'jugadores_list.html', {'jugadores': jugadores})


def lista_directores(request):
    directores = Directores.objects.all()
    return render(request, 'directores_list.html', {'directores': directores})

def lista_juegos(request):
    juegos = Juegos.objects.all()
    return render(request, 'juegos_list.html', {'juegos': juegos})

mi_app/templates/arbitros_list.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/list_player.css' %}">
</head>
 <h1>Lista de Jugadores</h1>
 <a class="boton-crear" href="{% url 'crear_arbitro' %}">Crear Arbitro</a>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Foto</th>
                <th>Liga</th>
            </tr>
        </thead>
        <tbody>
            {% for arbitro in arbitros %}
            <tr>
                <td>{{ arbitro.name }}</td>
               <td><img src="{{ arbitro.foto.url }}" alt="{{ arbitro.name }} - Foto"></td>
                <td><a href="{% url 'liga_detail' arbitro.liga_id.id %}">{{ arbitro.liga_id }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mi_app/templates/crear_arbitro.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/form_styles.css' %}">
</head>
<h1>Crear Arbitro</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

mi_app/templates/crear_director.html
{% extends './layouts/base.html' %}


{% block content%}

{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/form_styles.css' %}">
</head>
<h1>Crear Director</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

mi_app/templates/crear_equipo.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/form_styles.css' %}">
</head>
<h1>Crear Equipo</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

mi_app/templates/crear_estadio.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/form_styles.css' %}">
</head>
<h1>Crear Estadio</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

mi_app/templates/crear_juego.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/form_styles.css' %}">
</head>
<h1>Crear Juego</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

mi_app/templates/create_project.html
{% extends './layouts/base.html' %}

{% block content%}

    <h1>Create Project</h1>

    <form method="POST">
        {% csrf_token %}
        {{form}}
        <button>
            save
        </button>
    </form>

{% endblock %}

mi_app/templates/detail.html
{% extends './layouts/base.html' %}


{% block content%}
    <h1>{{project.name}}</h1>
    {% for task in tasks %}
    <div class="card">
        <ul>
        <li>{{task.titulo}}</li>
        </ul>
    </div>
    {% endfor %}
{% endblock %}

mi_app/templates/directores_list.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/list_player.css' %}">
</head>
 <h1>Lista de Directores</h1>
    <a class="boton-crear" href="{% url 'crear_director' %}">Crear Director</a>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Foto</th>
            </tr>
        </thead>
        <tbody>
            {% for director in directores %}
            <tr>
                <td>{{ director.name }}</td>
                <td><img src="{{ director.foto.url }}" alt="{{ director.name }} - Foto"></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mi_app/templates/equipos_list.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/list_player.css' %}">
</head>
<h1>Lista de Equipos</h1>
<a class="boton-crear" href="{% url 'crear_equipo' %}">Crear Equipo</a>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Director</th> 
                <th>Foto</th>
                <th>liga</th>
            </tr>
        </thead>
        <tbody>
            {% for equipo in equipos %}
            <tr>
                <td><a href="{% url 'equipo_detail' equipo.id %}">{{ equipo.name }}</a></td>
                <td>{{ equipo.directores }}</td>
                <td><img src="{{ equipo.foto.url }}" alt="{{ equipo.name }} - Foto"></td>
                <td><a href="{% url 'liga_detail' equipo.ligas.id %}">{{ equipo.ligas.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mi_app/templates/estadios_list.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/list_player.css' %}">
</head>
 <h1>Lista de Estadios</h1>
    <a class="boton-crear" href="{% url 'crear_estadio' %}">Crear Estadios</a>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Liga</th>
                <th>Foto</th>

            </tr>
        </thead>
        <tbody>
            {% for estadio in estadios %}
            <tr>
                <td>{{ estadio.name }}</td>
                <td><a href="{% url 'liga_detail' estadio.liga_id.id %}">{{ estadio.liga_id }}</a></td>
                <td><img src="{{ estadio.foto.url }}" alt="{{ estadio.name }} - Foto"></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mi_app/templates/juegos_list.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/list_player.css' %}">
</head>
 <h1>Lista de Partidos Programados</h1>
 <a class="boton-crear" href="{% url 'crear_juego' %}">Crear Partido</a>
    <table>
        <thead>
            <tr>
                <th>Folio</th>
                <th>Fecha</th>
                <th>Liga</th>
                <th>Visitante</th>
                <th>Local</th>
                <th>Estadio</th>
                <th>Arbitro</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody>
            {% for juego in juegos %}
            <tr>
                <td>{{ juego.folio }}</td>
                <td>{{ juego.fecha }}</td>
                <td><a href="{% url 'liga_detail' juego.liga_id.id %}">{{ juego.liga_id }}</a></td>
                <td><a href="{% url 'equipo_detail' juego.equipo1.id %}">{{ juego.equipo1 }}</a></td>
                <td><a href="{% url 'equipo_detail' juego.equipo2.id %}">{{ juego.equipo2 }}</a></td>
                <td>{{ juego.estadio }}</td>
                <td>{{ juego.arbitro }}</td>
                <td>{{ juego.state }}</td>               
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mi_app/templates/jugadores_list.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/list_player.css' %}">
</head>
 <h1>Lista de Jugadores</h1>
 <a class="boton-crear" href="{% url 'crear_jugador' %}">Crear Jugador</a>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Posición</th>
                <th>Número de Jugador</th>
                <th>Foto</th>
                <th>Equipo</th>
            </tr>
        </thead>
        <tbody>
            {% for jugador in jugadores %}
            <tr>
                <td>{{ jugador.name }}</td>
                <td>{{ jugador.get_posicion_display }}</td>
                <td>{{ jugador.num_player }}</td>
                <td><img src="{{ jugador.foto.url }}" alt="{{ jugador.name }} - Foto"></td>
                <td><a href="{% url 'equipo_detail' jugador.equipo_id.id %}">{{ jugador.equipo_id }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mi_app/templates/liga_list.html
{% extends './layouts/base.html' %}


{% block content%}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/list_player.css' %}">
</head>
 <h1>Lista de Ligas</h1>
 <a class="boton-crear" href="{% url 'crear_liga' %}">Crear Liga</a>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Foto</th>
            </tr>
        </thead>
        <tbody>
            {% for liga in ligas %}
            <tr>
                <td><a href="{% url 'liga_detail' liga.id %}">{{ liga.name }}</a></td>
                <td><img src="{{ liga.foto.url }}" alt="{{ liga.name }} - Foto"></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}